# Site settings
baseurl = "http://NormalHero.github.io/"
#contentdir = "content"
#publishdir = "public"
#layoutdir = "layouts"
#staticdir = "static"
#datadir = "data"
languageCode = "en-us"
title = "David Truong"
theme = "hugo-agency-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "David Truong"
	description = "Personal Website"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "david.truong510@gmail.com"

    # Link custom assets relative to /statuc
    custom_css = []
    custom_js  = []


	# Navigation
	[params.navigation]
		brand = "David Truong"
		services = "Skills"
		portfolio = "Portfolio"
		about = "About"
		team = "Team"
		contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #    url = "http://gohugo.io"
    #    name = "Hugo"
    #    weight = 10

    # postpended links
    [[menu.postpend]]
        url = "https://www.linkedin.com/in/david-truong-15964ab6"
        name = "LinkedIn"
        weight = 10


	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "Welcome To My Website"
		subtitle = "Take a Look Around"
		buttonText = "Show Me"


	# Services section
	[params.services]
        enable = true
		title = "Skills"
		subtitle = "Every profession has its tools"

        [[params.services.row]]

            [[params.services.row.list]]
                icon = "fa-laptop"
                title = "Programming Languages"
                description = "Proficient: Java, C++"
                description2 = "Famililar: HTML, CSS, Bootstrap, Javascript"

           	[[params.services.row.list]]
                icon = "fa-leaf"
                title = "Frameworks / APIs"
                description = "JPA/Hibernate, SOAP"
               	description2 = "Spring MVC"

            [[params.services.row.list]]
                icon = "fa-database"
                title = "Databases and Tools"
                description = "Oracle, MS SQL"
                description2 = "Junit, Maven, Jenkins, Tomcat, RabbitMQ, SVN, Git"


	# Portfolio section
	[params.portfolio]
        enable = true
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Portfolio"
		subtitle = "A few of my personal and professional works"

	[params.portfolio.modal]
        client = "Team"
        date = "Date"
        category = "Category"
        buttonText = "Close"


    # About section
	[params.about]
        enable = true
		title = "About"
		subtitle = "Bay Area native, software engineer, amateur cook, and aspiring entrepeneur"
		endpoint = "Looking<br>for<br>more!"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.
		[[params.about.events]]
			img = "about1.png"
			date = ""
			title = "About Me"
			description = "I am a Bay Area native working as a software engineer in the area. I attended the University of California Santa Barbara and came back to the Bay Area after graduating. In my spare time I enjoy cooking, going to the gym, and taking long walks on the beach."

		[[params.about.events]]
			img = "about2.png"
			date = "2007 - 2011"
			title = "Hayward High School"
			description = "I attended Hayward High School and was first introduced to programming in AP Computer Science. I enjoyed the problem solving, non-linear solutions, and the sheer amount of different technologies that I could use to write code with. I graduated top 5% of my class and decided to pursue a degree in computer science."

		[[params.about.events]]
			img = "about3.png"
			date = "2011 - 2015"
			title = "University of California Santa Barbara"
			description = "I attended UCSB for a Bachelors degree in CS. I gained a great deal of knowledge and met wonderful friends along the way. I had the chance to take interesting classes such as artifical intelligence, crytographic engineering, and security systems. After graduating, I moved back to the Bay Area to work as a software engineer."

		[[params.about.events]]
			img = "about4.png"
			date = "2015 - 2016"
			title = "ETrade"
			description = "I began working as a software engineer at ETrade. Most of my work is on the backend creating webservices, writing SQL database scripts, and automating daily tasks with batch jobs. My other responsibilities include writing unit tests, resolving defects, and participating in project system designs."


	# Team section
	[params.team]
        enable = false
		title = "Our amazing team"
		subtitle = "Lorem ipsum dolor sit amet consectetur."
		description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde."

		# All team member's pictures are stored under 'static/img/team'.
		# Replace them with your own too.
		[[params.team.members]]
			img = "1.jpg"
			name = "Kay Garland"
			position = "Lead Designer"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "#"],
				["fa-linkedin", "#"]
			]

		[[params.team.members]]
			img = "2.jpg"
			name = "Larry Parker"
			position = "Lead Marketer"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "#"],
				["fa-linkedin", "#"]
			]

		[[params.team.members]]
			img = "3.jpg"
			name = "Diana Pertersen"
			position = "Lead Developer"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "#"],
				["fa-linkedin", "#"]
			]

	# Client section
    [params.clients_list]
        enable = false

    	# All the clients' logos are stored under 'static/img/logos'.
    	# Replace them with your clients's logos.
    	[[params.clients]]
    		logo = "envato.jpg"
    		link = "#"

    	[[params.clients]]
    		logo = "designmodo.jpg"
    		link = "#"

    	[[params.clients]]
    		logo = "themeforest.jpg"
    		link = "#"

    	[[params.clients]]
    		logo = "creative-market.jpg"
    		link = "#"


	# Contact section
	[params.contact]
        enable = true
		title = "Contact Me"
		subtitle  = "Feel free to send me a message"
		buttonText = "Send message"

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone *"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
	[params.footer]
        enable = true
		copyright = "Published under the Apache License 2.0."

		#[[params.footer.social]]
		#	icon = "fa-twitter"
		#	link = "#"

		#[[params.footer.social]]
		#	icon = "fa-facebook"
		#	link = "#"

		[[params.footer.social]]
			icon = "fa-linkedin"
			link = "https://www.linkedin.com/in/david-truong-15964ab6"

		[[params.footer.quicklinks]]
			text = "Created using Hugo"
			link = "https://gohugo.io/"

		[[params.footer.quicklinks]]
			text = "Hosted on Github"
			link = "https://github.com/NormalHero/NormalHero.github.io-Source"
